### ISSUE TITLE
"Unknown highlighting tag"- warnings

### ISSUE THREAD

**Issue by DanielJonasMielke** [replit/codemirror-lang-solidity#2]
![Screenshot 2022-12-07 at 16 22 26](https://user-images.githubusercontent.com/84033390/206219326-3ceb1231-89ed-4c0a-a954-d93dc716ea46.png)
![Screenshot 2022-12-07 at 16 24 29](https://user-images.githubusercontent.com/84033390/206219588-d06b7825-8c4a-41b1-b8f5-0f0b82ef901d.png)

The syntaxhighlighting seems to work perfectly fine, appreciate your effort for releasing this pack! 
However I´m getting all these warnings in my browser, is it possible to somehow remove them?

**Comment by 2xic** [comment]
I also ran into this - has anyone found a solution to this problem ?
